name: CI
on: [push, pull_request]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.21.x' }
      - run: go mod download
      - run: go test ./...
      - run: go build ./cmd/sea-qa
      - name: Smoke run (apimock)
        run: ./sea-qa --spec suite.yaml --env env/staging.json --out reports || true
      - uses: actions/upload-artifact@v4
        with: { name: reports, path: reports/ }
